### ISSUE TITLE
A question about released pre-trained model

### ISSUE THREAD

**Issue by mrluin** [fenglinglwb/EDT#10]
Hello,

I have one question about released pre-trained model.

According to notes, `DNg15g25g50_EDTB_ImageNet200K` means the EDTB is pretrained on ImageNet200K with multi-related-task (Dng15g25g50). I found that the models you released are all pretrained in single task (such as dn, sr or deraining), but what i understand about pre-training is one random task for one batch of data (which is similar to IPT), did you try on that setting?

Thanks in advance.

**Comment by fenglinglwb** [comment]
Our model DNg15g25g50_EDTB_ImageNet200K is pre-trained on all tasks, containing multiple encoders and decoders. Please check carefully. 

And we trained the model on multiple tasks in a feed-forward, simultaneously, different from IPT that randomly chooses a task.

**Comment by mrluin** [comment]
Sorry, I am not sure yet.

> Our model DNg15g25g50_EDTB_ImageNet200K is pre-trained on all tasks,

Here, `pre-trained on all tasks` means including super-resolution and deraining? I checked that the ckpt of `DNg15g25g50_EDTB_ImageNet200K` only includes DN-related heads and tails.

**Comment by fenglinglwb** [comment]
'All tasks' that I said before refers to g15, g25 and g50 these three denoising tasks. They are highly related thus being denoted as multi-related-task 'Dng15g25g50'. It is none of the business of SR and deraining.

**Comment by fenglinglwb** [comment]
We released a model (SRx2x3DNg15_EDTB_ImageNet200K) trained on SR and denoising tasks. Actually, we had also trained a model on SR, denoising and draining tasks. But due to inferior performance on fine-tuning, we didn't release it.

**Comment by mrluin** [comment]
Thanks for your help~

By the way, do you have plan to provide training code and finetuning code?

**Comment by fenglinglwb** [comment]
We will release all the code and models but waiting for the paper's publication.
