### ISSUE TITLE
pre-train on ImageNet data?

### ISSUE THREAD

**Issue by jiamingNo1** [fenglinglwb/EDT#6]
I wonder how to pretrain on ImageNet dataset? 
1. for example, the Imagenet is always for object recognition, if our task is super-resolution, how do we construct the dataset?
2. the network is a hybrid (conv+transformer) architecture, when loading these pre-trained params, we load all the weights?

**Comment by fenglinglwb** [comment]
Thanks for your attention.
1. Sec.3.1 shows that "In terms of SR, we utilize bicubic interpolation to obtain low-resolution images. As for denoising and deraining, Gaussian noises (on RGB space) and rain streaks are directly added to the clean images."
2. Yes. Sec.3.1 shows that "The fine-tuning is performed on a single task, where the model is initialized with the pre-trained task-specific encoder and decoder as well as the shared transformer body."

**Comment by jiamingNo1** [comment]
okay，thank you

**Comment by jiamingNo1** [comment]
I have another question, how to choose 200k or 400k imagenet data, random or through some other way?

**Comment by fenglinglwb** [comment]
Randomly.

**Comment by jiamingNo1** [comment]
ok！
