### ISSUE TITLE
How to finetune based on pretrained model

### ISSUE THREAD

**Issue by mrluin** [fenglinglwb/EDT#8]
Hello, 

Thanks for your great work.

It seems strange that in EDT model only `len(self.noise_level)` of LQ inputs are processed, that is if the input is with shape of [8, 3, 192, 192] and self.noise_level = [15], only input[0] is processed, causing prediction has different shape from gts.

So, if i want to finetune based on multi-related-task pretrained mode (e.g., finetuning based on DNg15g25g50-ImageNet200K), how can i do that?

**Comment by fenglinglwb** [comment]
During finetuning period, we only adopted the task-specific (e.g., denoising) encoder and decoder, as well as the shared transformer body.

**Comment by mrluin** [comment]
Thanks for your quick response.

You mean that if i want to finetune on a specific task, I should discard other heads and tails and utilize the corresponding head, shared transformer body and corresponding tail to process the whole input, right?

Thus, the pipeline should be,

> input [8, 3, 192, 192] -> dn head -> transformer body -> dn tail -> predicition [8, 3, 192, 192]

And in implementation of EDT model, input LQ images are processed one-by-one. If in finetuning, i think input can be processed in batch, which should be more efficient (please correct me if my understand is wrong).

**Comment by fenglinglwb** [comment]
Yes. 

Actually, input LQ images are processed one task by one task (batch-wise), not one image by one image.

**Comment by mrluin** [comment]
All right, thank you very much.
