### ISSUE TITLE
Whici type of LearningScheduler is prefered in finetuning

### ISSUE THREAD

**Issue by mrluin** [fenglinglwb/EDT#9]
Hello,

Sorry about another question.

If i want to finetune the pretrained DNg15g25g50-ImageNet200K model onto a new noise-level, which type of learningscheduler is prefered, MultiStepLR or CosineAnnealing?

Thanks in advance!

**Comment by fenglinglwb** [comment]
In our implementation, we use constant lr for finetuning. You may try different schedulers and take the best. Maybe MultiStepLR is a good choice.

**Comment by mrluin** [comment]
Thanks for your help and i will have a try.
